name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Verify Dockerfile existence
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile is missing in GitHub Actions runner!"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push Docker Image
        run: |
          docker build -t my-app .
          docker tag my-app:latest 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
          docker push 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com
            docker pull 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 3000:3000 --name my-app 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
          EOF


