name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push Docker Image
        run: |
          docker build -t my-app .
          docker tag my-app:latest 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
          docker push 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.79.111.217 << 'EOF'
            docker pull 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 3000:3000 --name my-app 856238202384.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
          EOF
